// <auto-generated />
namespace AspMvcStarter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtwomorecolumntophototable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtwomorecolumntophototable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091512541_add two more column to photo table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
