// <auto-generated />
namespace AspMvcStarter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcommentnotificationliketable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcommentnotificationliketable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801071851586_add comment,notification,like table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
